### ISSUE TITLE
Requisition for MIG code base from 2021 workshop

### ISSUE THREAD

**Issue by aravindhank11** [argonne-lcf/CompPerfWorkshop#7]
Hi Murali / LCF Community,

Thank you very much for your contribution on https://www.youtube.com/watch?v=nYI0yt3Q82Y. I loved the video and wanted to try it out myself.

Is there a place from where I can clone the repo? The current 2022 repo doesn't seem to have MIG code (a quick glance didn't land me one)

Could you please help with the same?

Thanks!

**Comment by felker** [comment]
You can see the 2021 version of the public files here: https://github.com/argonne-lcf/CompPerfWorkshop/tree/v2021
